// packages/frontend/src/SignIn.tsx
import React from 'react';
import Title from '@airbnb/lunar/lib/components/Title';
import Text from '@airbnb/lunar/lib/components/Text';
import Button from '@airbnb/lunar/lib/components/Button';

export default function SignIn() {
    return (
        <div>
            <Title level={3}>Sign In To Continue</Title>
            <Text>UwU requires you to sign in with Twitch to view and manage your tokens.</Text>
            <Button href="/api/login">Sign In With Twitch</Button>
        </div>
    );
}

// packages/frontend/src/SignIn.svelte
<article class="uk-article">

    <h1 class="uk-article-title">
        VapeJuiceJordan Requires More From You
    </h1>

    <p class="uk-text-lead">
        You must sign in with your Twitch account to continue. Once signed in, you'll be able to view and manage your "Fuck With Me Tokens".
    </p>


    <div class="uk-grid-small uk-child-width-auto" uk-grid>
        <div>
            <a class="uk-button uk-button-primary uk-button-large" href="/api/login">Sign In</a>
        </div>
    </div>

</article>
