// packages/frontend/src/TotalTokens.svelte
<script>
    import client, { gql } from './client';
    const totalTokensQuery = client.query({
        query: gql`
            query TotalTokens {
                totalTokens
            }
        `,
    });
</script>

{#await totalTokensQuery then value}
    <p class="text-center my-4">
        <strong>Total tokens in circulation:</strong>
        {value.data.totalTokens}
    </p>
{/await}

// packages/frontend/src/TotalTokens.tsx
import React from 'react';
import { gql } from 'apollo-boost';
import { useQuery } from '@apollo/react-hooks';
import Loader from '@airbnb/lunar/lib/components/Loader';
import Text from '@airbnb/lunar/lib/components/Text';

export default function TotalTokens() {
    const { data, loading } = useQuery(gql`
        query TotalTokens {
            totalTokens
        }
    `);

    if (loading) {
        return <Loader />;
    }

    return (
        <Text>
            <strong>Total tokens in circulation:</strong> {data.totalTokens}
        </Text>
    );
}
